-- MySQL Script generated by MySQL Workbench
-- mar 28 may 2019 15:24:46 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema admin-conjuntos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema admin-conjuntos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `admin-conjuntos` DEFAULT CHARACTER SET utf8 ;
USE `admin-conjuntos` ;

-- -----------------------------------------------------
-- Table `admin-conjuntos`.`Administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin-conjuntos`.`Administrators` (
  `id_administrators` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `identification_number` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id_administrators`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin-conjuntos`.`towers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin-conjuntos`.`towers` (
  `id_towers` INT NOT NULL,
  `number` VARCHAR(45) NULL,
  PRIMARY KEY (`id_towers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin-conjuntos`.`Aptos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin-conjuntos`.`Aptos` (
  `id_aptos` INT NOT NULL,
  `number` VARCHAR(45) NULL,
  `towers_id_towers` INT NOT NULL,
  PRIMARY KEY (`id_aptos`),
  INDEX `fk_Aptos_towers_idx` (`towers_id_towers` ASC) ,
  CONSTRAINT `fk_Aptos_towers`
    FOREIGN KEY (`towers_id_towers`)
    REFERENCES `admin-conjuntos`.`towers` (`id_towers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin-conjuntos`.`residents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin-conjuntos`.`residents` (
  `id_residents` INT NOT NULL,
  `identification_number` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `residentscol` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `tel1` VARCHAR(45) NULL,
  `tel2` VARCHAR(45) NULL,
  `cell_phone_number` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Aptos_id_aptos` INT NOT NULL,
  PRIMARY KEY (`id_residents`),
  INDEX `fk_residents_Aptos1_idx` (`Aptos_id_aptos` ASC) ,
  CONSTRAINT `fk_residents_Aptos1`
    FOREIGN KEY (`Aptos_id_aptos`)
    REFERENCES `admin-conjuntos`.`Aptos` (`id_aptos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
